server:
 tomcat:
  max-threads: 10
  min-spare-threads: 10

 port: 8081

spring:
  application:
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@172.17.4.69:1521:easdb
#    url: jdbc:oracle:thin:@172.17.4.65:1521:easdb
    username: kingdee
    password: kingdee
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙，此处是filter修改的地方
      filters: stat
      #  commons-log.connection-logger-name: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
  mvc:
    async:
      request-timeout: 20000
  redis:
    database: 2
    host: localhost
    port: 6379
    password: sdjt1234
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
    timeout: 100000000

mybatis-plus:
 mapper-locations: classpath*:Mapper/*.xml
 type-aliases-package: com.example.EAS.model


